name: 'Test Runner'

on:
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Create ENV
        run: |
          touch .env
          echo PORT=4000 >> .env
          cat .env
      # - name: Install
      #  run: |
      #    npm ci
      #- name: Run Tests
      #  run: |
      #    npm run test
    
    


